# Generated by Django 2.2 on 2020-06-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
