# Generated by Django 2.2 on 2020-06-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200602_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='atm_card_number',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='atm_card_pin',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
