# Generated by Django 2.2 on 2020-06-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
