# Generated by Django 2.2 on 2020-06-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200602_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amount',
            field=models.IntegerField(default=5000),
        ),
    ]
