# Generated by Django 2.2 on 2020-06-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amount',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
